### ISSUE TITLE
Hello ,my dear friend~

### ISSUE THREAD

**Issue by dusoosoo** [lucasfporto/ACLDTool#3]
I am very appreciated of you , and I want to ask you do you have  the code of prievous work,such as active shape model, random forest ,Zernike and such other work ,any can be ok. I am encounter with some problems, thank you very much!

**Comment by lucasfporto** [comment]
Hello my friend what kind problem do you have ? what are you trying to do ?

**Comment by dusoosoo** [comment]
I want to realize the active shape model in this subject ,but when I edit the code ,which I download the inital code from github . I found it can't make the good effect on the lateral cephalogram,my math is bad ,So I want  to ask you whether know it ?

**Comment by lucasfporto** [comment]
Hello my shape model is composed by 28 cephalometric landmarks... I can send you the description just send me a message on WhatsApp +55 16 98119 9305... And yes the lateral is a problem (zygion) I'm waiting the reviewers about my paper to publish the code and the results

**Comment by dusoosoo** [comment]
> Hello my shape model is composed by 28 cephalometric landmarks... I can send you the description just send me a message on WhatsApp +55 16 98119 9305... And yes the lateral is a problem (zygion) I'm waiting the reviewers about my paper to publish the code and the results

there are some problem install the whatsapp in my country, would you please send me email,my email is 1402144585@qq.com,thank you very much！

**Comment by dusoosoo** [comment]
my friend,I was very dispirited now this time, I feel despair too,  I hope you can help with me,  I don't konw how to do the active shape model actually.
